### ISSUE TITLE
Order created date (symphony) needs correction in FOLIO 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#197]
order created date is mapped to Approval date and Date opened. In the latest load this was changed to the date loaded (due to Nolana issue discussed with Index Data?)

Acquisitions needs to maintain this information and would prefer to have it in a date field - see note below. They are also requesting it be included in a note (for the cases when this field is overwritten by un-open action). 

_Per Suzette: The order created date is important to Ordering because it's used for claims and clean up projects. Mapping the date to a date field makes reporting easy, compared to if it is mapped as a note. Zeynep says that the majority of orders will probably not be re-opened, so the approval date/date opened should be correct most of the time. They're asking if it's too much to do both: map it to the approval date/date opened and also as a note (example, "DATE CREATED: 1/23/2023")?_

**Comment by shelleydoljack** [comment]
The Symphony order date created is mapped to:
https://github.com/sul-dlss/folio-tasks/blob/ae77dd292238e2187cbdee153003323cf4e52d0e/tasks/helpers/orders/orders.rb#L59-L60
Recent discussion with IndexData was that FOLIO overwrites this data. Also, either FOLIO doesn't display dateOrdered or displays it as "Date Opened" in the UI. If we want to overwrite FOLIO's overwriting of our data, then we'll need to update the orders at orders-storage after we load them.

**Comment by shelleydoljack** [comment]
Also, "Created On" field is coming from the "metadata" block, so we are not touching that... but I guess we could... if we're going straight to orders-storage. I'd have to check if that data is actually possible to overwrite in orders-storage anyways.

**Comment by shelleydoljack** [comment]
Did some testing on folio-dev. We can update the approval date and date opened using `PUT /orders-storage/purchase-orders` endpoint. We cannot update those date fields using `PUT /orders/composite-orders` because FOLIO says we cannot update a write-protected field ("ongoing") but when I remove that field, it says "ongoing" field is required. :shrug: Also, FOLIO will probably overwrite the date fields anyways at the business logic endpoint. Lastly, we cannot update the "created on" date (the one in the metadata block) using `PUT /orders-storage/purchase-orders`. This is the order I futzed with: https://folio-dev.stanford.edu/orders/view/e63aa178-3648-5e27-b14c-f61a39f72824

Need to add to our migration checklist, run the task `rake acquisitions:update_orders[5, sul]` and `rake acquisitions:update_orders[5, law]` to update only purchase orders at the storage endpoint. This will work as longs as optimistic locking is not on the orders data models.

**Comment by ahafele** [comment]
Update Per @scanedastanford : If too complicated then they can make do with the Order created date being migrated into a FOLIO order line 1 note.

**Comment by scanedastanford** [comment]
I added the note in the mapping, line 18: https://docs.google.com/spreadsheets/d/13bh1Dd-v_tC0A5iepeTxWVBjj2JLz3lmvFglFDjOcD4/edit#gid=215993364

**Comment by shelleydoljack** [comment]
Fixed by #198
