### ISSUE TITLE
Need task to move Organization Interfaces from folio-test to stage etc. 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#209]
e.g. https://folio-test.stanford.edu/organizations/view/8a8dc6dd-8be6-4bd9-80cd-e00409b37dc6

In the above case, SFX Marcit is a new vendor also. Should this just get created in Symphony instead so it becomes part of the migration? 

Example for an existing Vendor/Organization

https://folio-test.stanford.edu/organizations/view/2b8f6523-bb92-49cd-a073-32e11aa52f82

**Comment by shelleydoljack** [comment]
When we originally talked about the EDI info for the vendors, I recall that we said we'll just have acquisitions add the data in FOLIO by hand since it was a few vendors. However, we probably want to have a task to move interfaces from folio-test to -stage and -prod so that the UUID's are the same across environments. Hmm, it doesn't look like we are keeping the organization UUID's the same across environments. Do we need to do this? @jermnelson Can the vendor load app in libsys-airflow handle different organization UUID's across environments? Or should we create organization UUID with the formula code + okapi url + type enum? 

I'm not sure about creating SFX Marcit as a new vendor in Symphony because they are tied to vendor fiscal years and I don't know what that means in terms of when we roll over vendors for the next fiscal cycle and what if they don't have orders.

**Comment by jermnelson** [comment]
@shelleydoljack, the current plan is for the vendor load app to use Folio's oOganizations and Interfaces as the "source-of-truth" so the Organization's UUIDs shouldn't matter within the context of the app.

**Comment by ahafele** [comment]
pre-req for infra to move to -stage

**Comment by ahafele** [comment]
We should retain the interface UUIDs if possible. I think that is the plan anyway?

**Comment by shelleydoljack** [comment]
Yes, the interface UUIDs will be retained across all envs.

**Comment by ahafele** [comment]
@shelleydoljack thanks! can we close this now? Does it need a line in the migration checklist that includes linked interfaces maybe?

**Comment by shelleydoljack** [comment]
Let me get the PR done first.
