### ISSUE TITLE
Create rake task to assign sul_admin user to all Acq Units

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss-deprecated/folio-migration-tasks#27]

**Comment by dlrueda** [comment]
Look at Ryan’s code that assigns permission sets and acq unit to see how to do it.

Assign ALL the different acq units: SUL, Lane, Law, Business

**Comment by ryanmax** [comment]
I added multiple rows for sul_admin to our permissions matrix spreadsheet. I think that should do it.

**Comment by jgreben** [comment]
@ryanmax can you send the link to that spreadsheet?
I re-ordered the Migration Data Load checklist (https://docs.google.com/spreadsheets/d/1_6QWDtS9zRcwgvc8pDdbKq10A6629y4OU39DsNBApF0) to reflect the fact that all users must be loaded before any of the acquisitions data so that the `tsv_users:assign_acquisition_units` task can be run first.

**Comment by jgreben** [comment]
@ryanmax Thanks, I found the new spreadsheet here: https://docs.google.com/spreadsheets/d/1jfU6Bww6gXd81HREYVp8OBItYTFNJwwqMTLxJncZomQ

**Comment by jgreben** [comment]
This was accomplished by adding the lines to the pset assignment spreadsheet.
