### ISSUE TITLE
Rake task to load extracted circ data

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss-deprecated/folio-migration-tasks#47]

**Comment by dlrueda** [comment]
Once the correct circ reference data has been extracted from current/old FOLIO instance, create rake task to load it to new FOLIO instance.

Add to data migration plan document
https://docs.google.com/document/d/17bBS9wyeZ2m1d20xDggVwau61OSsU-pqYiigE8fzV1E/edit#heading=h.uzemydbrqupu

Add to Migration Data Load Checklist https://docs.google.com/spreadsheets/d/1_6QWDtS9zRcwgvc8pDdbKq10A6629y4OU39DsNBApF0/edit#gid=0

**Comment by shelleydoljack** [comment]
The circulation rules json data only has UUID's for all the other settings data it relies upon, such as patron group, locations, material types, etc. In order to load the circ rules, we need to figure out what the UUID's are for those other settings in the new FOLIO instance or re-write code to preserve UUID's for those other settings across FOLIO instances.

**Comment by jgreben** [comment]
Also please add the rake task steps to the migration checklist: https://docs.google.com/spreadsheets/d/1_6QWDtS9zRcwgvc8pDdbKq10A6629y4OU39DsNBApF0/edit#gid=0
