### ISSUE TITLE
Change tasks/helpers/tsv_user.rb service_points_assign method to use /service-point-users endpoint

### ISSUE THREAD

**Issue by jgreben** [sul-dlss-deprecated/folio-migration-tasks#64]
The `tasks/users/assign_permission_sets.rake` rake task is assigning the default service point for user requests, not the user's overall default service point. We need to change the post to use the `/service-point-users` endpoint and remove the PUT to `/request-preference-storage`

**Comment by shelleydoljack** [comment]
Closed by #65

**Comment by jgreben** [comment]
When I ran this on `folio-test` I get this error for every user:
```
{"errors"=>
  [{"message"=>
     "lower(f_unaccent(jsonb ->> 'userId'::text)) value already exists in table service_point_user: 2f6de03c-f4cc-430a-9784-664b1d48b8c2",
    "type"=>"1",
    "code"=>"-1",
    "parameters"=>
     [{"key"=>"lower(f_unaccent(jsonb ->> 'userId'::text))",
       "value"=>"2f6de03c-f4cc-430a-9784-664b1d48b8c2"}]}]}
```

**Comment by shelleydoljack** [comment]
This happens when the userId already exists in the service-point-user table. We are POST'ing to that endpoint and not handling modifications. I'm surprised that it is giving this error for every user if none or mostly all of the users do not have default service points. Weirdly, I'm getting a 404 not found when querying the users table and service point users table for this user ID. Did you delete this user?

**Comment by jgreben** [comment]
My mistake. I was accidentally re-loading into the dev instance where I had already loaded them....
